version: '2'

services:
  app:
    image: 'platform:latest'
    ports:
    - "5561:5561"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    env_file:
      - .env.app
#    restart: unless-stopped



  db:
    image: 'postgres:11.4-alpine'
    ports:
    - "5432:5432"
    container_name: db
    env_file:
      - .env.db
#    restart: unless-stopped


