version: '2'

services:
  app:
    image: 'platform:latest'
    ports:
    - "5561:5561"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    env_file:
      - .env.app
#    restart: unless-stopped
  db:
    image: 'postgres:13.1-alpine'
    ports:
    - "5432"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dev_social
#    env_file:
#      - .env.db
#    restart: unless-stopped
